---
abstract: 'document your modules like KEEDI does '
author:
  - 'Keedi Kim - 김도형 <keedi@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Weaver-PluginBundle-KEEDI
requires:
  Pod::Weaver::Config::Assembler: 0
  namespace::autoclean: 0
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Status=Active&Queue=Pod-Weaver-PluginBundle-KEEDI
  homepage: https://metacpan.org/module/Pod::Weaver::PluginBundle::KEEDI
  repository: http://github.com/keedi/Pod-Weaver-PluginBundle-KEEDI.git
version: 0.003
